// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/protobuf/phone.proto

package blatherpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRoomReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomReq) Reset()         { *m = CreateRoomReq{} }
func (m *CreateRoomReq) String() string { return proto.CompactTextString(m) }
func (*CreateRoomReq) ProtoMessage()    {}
func (*CreateRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_89768df7eb7899af, []int{0}
}

func (m *CreateRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomReq.Unmarshal(m, b)
}
func (m *CreateRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomReq.Marshal(b, m, deterministic)
}
func (m *CreateRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomReq.Merge(m, src)
}
func (m *CreateRoomReq) XXX_Size() int {
	return xxx_messageInfo_CreateRoomReq.Size(m)
}
func (m *CreateRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomReq proto.InternalMessageInfo

type CreateRoomResp struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomResp) Reset()         { *m = CreateRoomResp{} }
func (m *CreateRoomResp) String() string { return proto.CompactTextString(m) }
func (*CreateRoomResp) ProtoMessage()    {}
func (*CreateRoomResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_89768df7eb7899af, []int{1}
}

func (m *CreateRoomResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomResp.Unmarshal(m, b)
}
func (m *CreateRoomResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomResp.Marshal(b, m, deterministic)
}
func (m *CreateRoomResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomResp.Merge(m, src)
}
func (m *CreateRoomResp) XXX_Size() int {
	return xxx_messageInfo_CreateRoomResp.Size(m)
}
func (m *CreateRoomResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomResp proto.InternalMessageInfo

func (m *CreateRoomResp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CallData struct {
	UserId               uint64       `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AudioData            *AudioData   `protobuf:"bytes,2,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	Coordinates          *Coordinates `protobuf:"bytes,3,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CallData) Reset()         { *m = CallData{} }
func (m *CallData) String() string { return proto.CompactTextString(m) }
func (*CallData) ProtoMessage()    {}
func (*CallData) Descriptor() ([]byte, []int) {
	return fileDescriptor_89768df7eb7899af, []int{2}
}

func (m *CallData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallData.Unmarshal(m, b)
}
func (m *CallData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallData.Marshal(b, m, deterministic)
}
func (m *CallData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallData.Merge(m, src)
}
func (m *CallData) XXX_Size() int {
	return xxx_messageInfo_CallData.Size(m)
}
func (m *CallData) XXX_DiscardUnknown() {
	xxx_messageInfo_CallData.DiscardUnknown(m)
}

var xxx_messageInfo_CallData proto.InternalMessageInfo

func (m *CallData) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CallData) GetAudioData() *AudioData {
	if m != nil {
		return m.AudioData
	}
	return nil
}

func (m *CallData) GetCoordinates() *Coordinates {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

type AudioData struct {
	Samples              []*Sample `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	NumSamples           uint32    `protobuf:"varint,2,opt,name=num_samples,json=numSamples,proto3" json:"num_samples,omitempty"`
	SampleRate           uint32    `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AudioData) Reset()         { *m = AudioData{} }
func (m *AudioData) String() string { return proto.CompactTextString(m) }
func (*AudioData) ProtoMessage()    {}
func (*AudioData) Descriptor() ([]byte, []int) {
	return fileDescriptor_89768df7eb7899af, []int{3}
}

func (m *AudioData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AudioData.Unmarshal(m, b)
}
func (m *AudioData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AudioData.Marshal(b, m, deterministic)
}
func (m *AudioData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AudioData.Merge(m, src)
}
func (m *AudioData) XXX_Size() int {
	return xxx_messageInfo_AudioData.Size(m)
}
func (m *AudioData) XXX_DiscardUnknown() {
	xxx_messageInfo_AudioData.DiscardUnknown(m)
}

var xxx_messageInfo_AudioData proto.InternalMessageInfo

func (m *AudioData) GetSamples() []*Sample {
	if m != nil {
		return m.Samples
	}
	return nil
}

func (m *AudioData) GetNumSamples() uint32 {
	if m != nil {
		return m.NumSamples
	}
	return 0
}

func (m *AudioData) GetSampleRate() uint32 {
	if m != nil {
		return m.SampleRate
	}
	return 0
}

type Sample struct {
	LeftChannel          float64  `protobuf:"fixed64,1,opt,name=left_channel,json=leftChannel,proto3" json:"left_channel,omitempty"`
	RightChannel         float64  `protobuf:"fixed64,2,opt,name=right_channel,json=rightChannel,proto3" json:"right_channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sample) Reset()         { *m = Sample{} }
func (m *Sample) String() string { return proto.CompactTextString(m) }
func (*Sample) ProtoMessage()    {}
func (*Sample) Descriptor() ([]byte, []int) {
	return fileDescriptor_89768df7eb7899af, []int{4}
}

func (m *Sample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sample.Unmarshal(m, b)
}
func (m *Sample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sample.Marshal(b, m, deterministic)
}
func (m *Sample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sample.Merge(m, src)
}
func (m *Sample) XXX_Size() int {
	return xxx_messageInfo_Sample.Size(m)
}
func (m *Sample) XXX_DiscardUnknown() {
	xxx_messageInfo_Sample.DiscardUnknown(m)
}

var xxx_messageInfo_Sample proto.InternalMessageInfo

func (m *Sample) GetLeftChannel() float64 {
	if m != nil {
		return m.LeftChannel
	}
	return 0
}

func (m *Sample) GetRightChannel() float64 {
	if m != nil {
		return m.RightChannel
	}
	return 0
}

type Coordinates struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float64  `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinates) Reset()         { *m = Coordinates{} }
func (m *Coordinates) String() string { return proto.CompactTextString(m) }
func (*Coordinates) ProtoMessage()    {}
func (*Coordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_89768df7eb7899af, []int{5}
}

func (m *Coordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinates.Unmarshal(m, b)
}
func (m *Coordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinates.Marshal(b, m, deterministic)
}
func (m *Coordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinates.Merge(m, src)
}
func (m *Coordinates) XXX_Size() int {
	return xxx_messageInfo_Coordinates.Size(m)
}
func (m *Coordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinates.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinates proto.InternalMessageInfo

func (m *Coordinates) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Coordinates) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Coordinates) GetZ() float64 {
	if m != nil {
		return m.Z
	}
	return 0
}

type UserSettingsData struct {
	Mute                 bool            `protobuf:"varint,1,opt,name=mute,proto3" json:"mute,omitempty"`
	MuteList             map[uint64]bool `protobuf:"bytes,2,rep,name=mute_list,json=muteList,proto3" json:"mute_list,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserSettingsData) Reset()         { *m = UserSettingsData{} }
func (m *UserSettingsData) String() string { return proto.CompactTextString(m) }
func (*UserSettingsData) ProtoMessage()    {}
func (*UserSettingsData) Descriptor() ([]byte, []int) {
	return fileDescriptor_89768df7eb7899af, []int{6}
}

func (m *UserSettingsData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSettingsData.Unmarshal(m, b)
}
func (m *UserSettingsData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSettingsData.Marshal(b, m, deterministic)
}
func (m *UserSettingsData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSettingsData.Merge(m, src)
}
func (m *UserSettingsData) XXX_Size() int {
	return xxx_messageInfo_UserSettingsData.Size(m)
}
func (m *UserSettingsData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSettingsData.DiscardUnknown(m)
}

var xxx_messageInfo_UserSettingsData proto.InternalMessageInfo

func (m *UserSettingsData) GetMute() bool {
	if m != nil {
		return m.Mute
	}
	return false
}

func (m *UserSettingsData) GetMuteList() map[uint64]bool {
	if m != nil {
		return m.MuteList
	}
	return nil
}

type UserSettingsResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSettingsResponse) Reset()         { *m = UserSettingsResponse{} }
func (m *UserSettingsResponse) String() string { return proto.CompactTextString(m) }
func (*UserSettingsResponse) ProtoMessage()    {}
func (*UserSettingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_89768df7eb7899af, []int{7}
}

func (m *UserSettingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSettingsResponse.Unmarshal(m, b)
}
func (m *UserSettingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSettingsResponse.Marshal(b, m, deterministic)
}
func (m *UserSettingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSettingsResponse.Merge(m, src)
}
func (m *UserSettingsResponse) XXX_Size() int {
	return xxx_messageInfo_UserSettingsResponse.Size(m)
}
func (m *UserSettingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSettingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserSettingsResponse proto.InternalMessageInfo

func (m *UserSettingsResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*CreateRoomReq)(nil), "blatherpb.CreateRoomReq")
	proto.RegisterType((*CreateRoomResp)(nil), "blatherpb.CreateRoomResp")
	proto.RegisterType((*CallData)(nil), "blatherpb.CallData")
	proto.RegisterType((*AudioData)(nil), "blatherpb.AudioData")
	proto.RegisterType((*Sample)(nil), "blatherpb.Sample")
	proto.RegisterType((*Coordinates)(nil), "blatherpb.Coordinates")
	proto.RegisterType((*UserSettingsData)(nil), "blatherpb.UserSettingsData")
	proto.RegisterMapType((map[uint64]bool)(nil), "blatherpb.UserSettingsData.MuteListEntry")
	proto.RegisterType((*UserSettingsResponse)(nil), "blatherpb.UserSettingsResponse")
}

func init() { proto.RegisterFile("pkg/protobuf/phone.proto", fileDescriptor_89768df7eb7899af) }

var fileDescriptor_89768df7eb7899af = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x51, 0x6f, 0xd3, 0x3c,
	0x14, 0x95, 0xd3, 0xae, 0x6b, 0x6f, 0x9a, 0x7e, 0xfb, 0x4c, 0x05, 0xa1, 0x3c, 0xac, 0x04, 0x09,
	0x15, 0x21, 0x75, 0xa8, 0x43, 0x62, 0x62, 0x4f, 0xa3, 0x80, 0x84, 0x04, 0x68, 0x72, 0xb5, 0x17,
	0x5e, 0x22, 0x77, 0xb9, 0x6b, 0xa3, 0x26, 0x71, 0x88, 0x1d, 0xb4, 0xf6, 0x67, 0xf0, 0x37, 0xf8,
	0x33, 0xfc, 0x24, 0x64, 0x37, 0x69, 0x0d, 0x62, 0x3c, 0xc5, 0xf7, 0x9e, 0x73, 0x8f, 0x8f, 0xaf,
	0x4e, 0xc0, 0xcf, 0x57, 0x8b, 0x93, 0xbc, 0x10, 0x4a, 0xcc, 0xcb, 0x9b, 0x93, 0x7c, 0x29, 0x32,
	0x1c, 0x9b, 0x92, 0x76, 0xe6, 0x09, 0x57, 0x4b, 0x2c, 0xf2, 0x79, 0xf0, 0x1f, 0x78, 0xd3, 0x02,
	0xb9, 0x42, 0x26, 0x44, 0xca, 0xf0, 0x6b, 0x30, 0x84, 0x9e, 0xdd, 0x90, 0x39, 0xed, 0x81, 0x13,
	0x47, 0x3e, 0x19, 0x92, 0x51, 0x87, 0x39, 0x71, 0x14, 0x7c, 0x27, 0xd0, 0x9e, 0xf2, 0x24, 0x79,
	0xcb, 0x15, 0xa7, 0x0f, 0xe0, 0xb0, 0x94, 0x58, 0x84, 0x15, 0xa3, 0xc9, 0x5a, 0xba, 0xfc, 0x10,
	0xd1, 0x53, 0x00, 0x5e, 0x46, 0xb1, 0x08, 0x23, 0xae, 0xb8, 0xef, 0x0c, 0xc9, 0xc8, 0x9d, 0xf4,
	0xc7, 0xbb, 0x8b, 0xc7, 0x17, 0x1a, 0xd4, 0x12, 0xac, 0xc3, 0xeb, 0x23, 0x3d, 0x03, 0xf7, 0x5a,
	0x88, 0x22, 0x8a, 0x33, 0xae, 0x50, 0xfa, 0x0d, 0x33, 0x75, 0xdf, 0x9a, 0x9a, 0xee, 0x51, 0x66,
	0x53, 0x83, 0x0d, 0x74, 0x76, 0x8a, 0xf4, 0x39, 0x1c, 0x4a, 0x9e, 0xe6, 0x09, 0x4a, 0x9f, 0x0c,
	0x1b, 0x23, 0x77, 0xf2, 0xbf, 0x25, 0x31, 0x33, 0x08, 0xab, 0x19, 0xf4, 0x18, 0xdc, 0xac, 0x4c,
	0xc3, 0x7a, 0x40, 0x3b, 0xf5, 0x18, 0x64, 0x65, 0x3a, 0xdb, 0x13, 0xb6, 0x60, 0x58, 0x70, 0x85,
	0xc6, 0x94, 0xc7, 0x60, 0xdb, 0x62, 0x5c, 0x61, 0x70, 0x09, 0xad, 0x2d, 0x97, 0x3e, 0x86, 0x6e,
	0x82, 0x37, 0x2a, 0xbc, 0x5e, 0xf2, 0x2c, 0xc3, 0xc4, 0xac, 0x84, 0x30, 0x57, 0xf7, 0xa6, 0xdb,
	0x16, 0x7d, 0x02, 0x5e, 0x11, 0x2f, 0x96, 0x7b, 0x8e, 0x63, 0x38, 0x5d, 0xd3, 0xac, 0x48, 0xc1,
	0x2b, 0x70, 0xad, 0x97, 0xd2, 0x2e, 0x90, 0xdb, 0x4a, 0x8b, 0xdc, 0xea, 0x6a, 0x5d, 0x4d, 0x91,
	0xb5, 0xae, 0x36, 0xc6, 0x13, 0x61, 0x64, 0x13, 0xfc, 0x20, 0x70, 0x74, 0x25, 0xb1, 0x98, 0xa1,
	0x52, 0x71, 0xb6, 0x90, 0x66, 0x1d, 0x14, 0x9a, 0x69, 0xa9, 0xd0, 0x28, 0xb4, 0x99, 0x39, 0xd3,
	0xf7, 0xd0, 0xd1, 0xdf, 0x30, 0x89, 0xa5, 0xf2, 0x1d, 0xb3, 0xa4, 0x67, 0xd6, 0x92, 0xfe, 0xd4,
	0x18, 0x7f, 0x2a, 0x15, 0x7e, 0x8c, 0xa5, 0x7a, 0x97, 0xa9, 0x62, 0xcd, 0xda, 0x69, 0x55, 0x0e,
	0xce, 0xc1, 0xfb, 0x0d, 0xa2, 0x47, 0xd0, 0x58, 0xe1, 0xba, 0x0a, 0x83, 0x3e, 0xd2, 0x3e, 0x1c,
	0x7c, 0xe3, 0x49, 0x89, 0xc6, 0x73, 0x9b, 0x6d, 0x8b, 0xd7, 0xce, 0x19, 0x09, 0x9e, 0x42, 0xdf,
	0xbe, 0x48, 0xa7, 0x4d, 0x64, 0x12, 0x75, 0xe2, 0xc4, 0xaa, 0xb2, 0xeb, 0x88, 0xd5, 0xe4, 0x27,
	0x81, 0x83, 0x4b, 0x9d, 0x5f, 0x7a, 0x01, 0xb0, 0x4f, 0x27, 0xf5, 0xed, 0x64, 0xd8, 0x29, 0x1e,
	0x3c, 0xbc, 0x03, 0x91, 0x39, 0x7d, 0x09, 0x4d, 0x9d, 0x5e, 0x7a, 0xcf, 0xa6, 0x54, 0x71, 0x1e,
	0xfc, 0xad, 0x39, 0x22, 0x2f, 0x08, 0xfd, 0x0c, 0xbd, 0xab, 0x3c, 0xe2, 0x0a, 0x6b, 0xb3, 0xf4,
	0xd1, 0x3f, 0xd6, 0x35, 0x38, 0xbe, 0x03, 0xac, 0x9f, 0xf8, 0xc6, 0xfb, 0xe2, 0x8e, 0xcf, 0x77,
	0x9c, 0x79, 0xcb, 0xfc, 0x98, 0xa7, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x58, 0x82, 0x26, 0x9d,
	0xb4, 0x03, 0x00, 0x00,
}
