// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package blatherpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// PhoneClient is the client API for Phone service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PhoneClient interface {
	CreateRoom(ctx context.Context, in *CreateRoomReq, opts ...grpc.CallOption) (*CreateRoomResp, error)
	Call(ctx context.Context, opts ...grpc.CallOption) (Phone_CallClient, error)
	UpdateSettings(ctx context.Context, in *UserSettingsData, opts ...grpc.CallOption) (*UserSettingsResponse, error)
	Coordination(ctx context.Context, opts ...grpc.CallOption) (Phone_CoordinationClient, error)
}

type phoneClient struct {
	cc grpc.ClientConnInterface
}

func NewPhoneClient(cc grpc.ClientConnInterface) PhoneClient {
	return &phoneClient{cc}
}

func (c *phoneClient) CreateRoom(ctx context.Context, in *CreateRoomReq, opts ...grpc.CallOption) (*CreateRoomResp, error) {
	out := new(CreateRoomResp)
	err := c.cc.Invoke(ctx, "/blatherpb.Phone/CreateRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phoneClient) Call(ctx context.Context, opts ...grpc.CallOption) (Phone_CallClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Phone_serviceDesc.Streams[0], "/blatherpb.Phone/Call", opts...)
	if err != nil {
		return nil, err
	}
	x := &phoneCallClient{stream}
	return x, nil
}

type Phone_CallClient interface {
	Send(*CallData) error
	Recv() (*CallData, error)
	grpc.ClientStream
}

type phoneCallClient struct {
	grpc.ClientStream
}

func (x *phoneCallClient) Send(m *CallData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *phoneCallClient) Recv() (*CallData, error) {
	m := new(CallData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *phoneClient) UpdateSettings(ctx context.Context, in *UserSettingsData, opts ...grpc.CallOption) (*UserSettingsResponse, error) {
	out := new(UserSettingsResponse)
	err := c.cc.Invoke(ctx, "/blatherpb.Phone/UpdateSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phoneClient) Coordination(ctx context.Context, opts ...grpc.CallOption) (Phone_CoordinationClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Phone_serviceDesc.Streams[1], "/blatherpb.Phone/Coordination", opts...)
	if err != nil {
		return nil, err
	}
	x := &phoneCoordinationClient{stream}
	return x, nil
}

type Phone_CoordinationClient interface {
	Send(*Coordinates) error
	Recv() (*Coordinates, error)
	grpc.ClientStream
}

type phoneCoordinationClient struct {
	grpc.ClientStream
}

func (x *phoneCoordinationClient) Send(m *Coordinates) error {
	return x.ClientStream.SendMsg(m)
}

func (x *phoneCoordinationClient) Recv() (*Coordinates, error) {
	m := new(Coordinates)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PhoneServer is the server API for Phone service.
// All implementations should embed UnimplementedPhoneServer
// for forward compatibility
type PhoneServer interface {
	CreateRoom(context.Context, *CreateRoomReq) (*CreateRoomResp, error)
	Call(Phone_CallServer) error
	UpdateSettings(context.Context, *UserSettingsData) (*UserSettingsResponse, error)
	Coordination(Phone_CoordinationServer) error
}

// UnimplementedPhoneServer should be embedded to have forward compatible implementations.
type UnimplementedPhoneServer struct {
}

func (UnimplementedPhoneServer) CreateRoom(context.Context, *CreateRoomReq) (*CreateRoomResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoom not implemented")
}
func (UnimplementedPhoneServer) Call(Phone_CallServer) error {
	return status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedPhoneServer) UpdateSettings(context.Context, *UserSettingsData) (*UserSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSettings not implemented")
}
func (UnimplementedPhoneServer) Coordination(Phone_CoordinationServer) error {
	return status.Errorf(codes.Unimplemented, "method Coordination not implemented")
}

// UnsafePhoneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PhoneServer will
// result in compilation errors.
type UnsafePhoneServer interface {
	mustEmbedUnimplementedPhoneServer()
}

func RegisterPhoneServer(s grpc.ServiceRegistrar, srv PhoneServer) {
	s.RegisterService(&_Phone_serviceDesc, srv)
}

func _Phone_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blatherpb.Phone/CreateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneServer).CreateRoom(ctx, req.(*CreateRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Phone_Call_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PhoneServer).Call(&phoneCallServer{stream})
}

type Phone_CallServer interface {
	Send(*CallData) error
	Recv() (*CallData, error)
	grpc.ServerStream
}

type phoneCallServer struct {
	grpc.ServerStream
}

func (x *phoneCallServer) Send(m *CallData) error {
	return x.ServerStream.SendMsg(m)
}

func (x *phoneCallServer) Recv() (*CallData, error) {
	m := new(CallData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Phone_UpdateSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSettingsData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneServer).UpdateSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blatherpb.Phone/UpdateSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneServer).UpdateSettings(ctx, req.(*UserSettingsData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Phone_Coordination_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PhoneServer).Coordination(&phoneCoordinationServer{stream})
}

type Phone_CoordinationServer interface {
	Send(*Coordinates) error
	Recv() (*Coordinates, error)
	grpc.ServerStream
}

type phoneCoordinationServer struct {
	grpc.ServerStream
}

func (x *phoneCoordinationServer) Send(m *Coordinates) error {
	return x.ServerStream.SendMsg(m)
}

func (x *phoneCoordinationServer) Recv() (*Coordinates, error) {
	m := new(Coordinates)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Phone_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blatherpb.Phone",
	HandlerType: (*PhoneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoom",
			Handler:    _Phone_CreateRoom_Handler,
		},
		{
			MethodName: "UpdateSettings",
			Handler:    _Phone_UpdateSettings_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Call",
			Handler:       _Phone_Call_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Coordination",
			Handler:       _Phone_Coordination_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/protobuf/phone.proto",
}
